name             'chef-vector'
maintainer       'Justin Alan Ryan'
maintainer_email 'bitmonk@icloud.com'
license          'All rights reserved'
description      'Installs/Configures chef-vector'
long_description 'Installs/Configures chef-vector'
version          '0.1.0'
